### ISSUE TITLE
break & continue outside loop

### ISSUE THREAD

**Issue by haifenghuang** [TomPrograms/dragon#1]
If I use `break` and `continue` outside a loop(e.g. `while` loop or `for` loop), what is the result of the dragon program?

I see no handling of this problem in dragon source.

**Comment by TomPrograms** [comment]
There actually isn't handling of this - you will either receive the error:
`[File: test.drg] [Line: 1] Error at 'break': 'break' must be inside a loop.` 
or
`[File: test.drg] [Line: 1] Error at 'continue': 'continue' must be inside a loop.`
